package:
  version: "{{ load_setup_py_data().version }}"
  name: 'denspart'

source:
  path: ../../

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - numpy
    - scipy
    - cython >=0.24.1
    - setuptools
    - nose
    - horton
  run:
    - python
    - numpy
    - scipy
    - nose
    - horton

about:
  home: https://github.com/theochem/denspart_horton
  license: GNU Version 3
