name: Build and Deploy Docs

on:
  push:
    branches:
      - main  # Set your default branch here

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Set your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r docs/requirements.txt

    - name: Install Pandoc
      run: |
        # For ubuntu-latest
        # sudo apt update
        # sudo apt-get install pandoc
        brew install pandoc

    - name: Build documentation
      run: |
        cd docs
        bash install.sh
        cd ../

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html/
        force_orphan: true
