name: Build and Deploy Docs

on:
  push:
    branches:
      - main  # Set your default branch here

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Set your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        # for sphinx docs builder
        pip install sphinx==7.2.6
        pip install sphinx-autodoc-typehints==1.25.2
        pip install nbsphinx==0.9.3
        pip install sphinx_rtd_theme==2.0.0
        pip install nbconvert==7.12.0
        pip install notebook

    - name: Install Pandoc
      run: |
        # For ubuntu-latest
        # sudo apt update
        # sudo apt-get install pandoc
        brew install pandoc

    - name: Build documentation
      run: |
        cd docs
        bash gen_api.sh
        cd notebooks
        jupyter nbconvert --to notebook --execute --inplace --allow-errors *.ipynb
        cd ../
        make html  # Or sphinx-build command based on your setup
        cd ../

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html/
        force_orphan: true
