name: Build and Deploy Docs

on:
  push:
    branches:
      - main  # Set your default branch here

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Set your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx==7.2.6
        pip install sphinx-autodoc-typehints==1.25.2
        pip install nbsphinx==0.9.3
        pip install sphinx_rtd_theme==2.0.0
        pip install nbconvert==7.12.0

    - name: Build documentation
      run: |
        make html  # Or sphinx-build command based on your setup

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html  # Update to your build output directory
